USE [master]
GO

/****** Object:  Database [GMC Consignment Information]    Script Date: 11/19/2017 12:55:23 PM ******/
CREATE DATABASE [GMC Consignment Information]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GMC Consignment Information', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\GMC Consignment Information.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GMC Consignment Information_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\GMC Consignment Information_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GMC Consignment Information] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GMC Consignment Information].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GMC Consignment Information] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET ARITHABORT OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GMC Consignment Information] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GMC Consignment Information] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GMC Consignment Information] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GMC Consignment Information] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GMC Consignment Information] SET  MULTI_USER 
GO

ALTER DATABASE [GMC Consignment Information] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GMC Consignment Information] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GMC Consignment Information] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GMC Consignment Information] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GMC Consignment Information] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GMC Consignment Information] SET QUERY_STORE = OFF
GO

USE [GMC Consignment Information]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GMC Consignment Information] SET  READ_WRITE 
GO

